- hosts: gluster_nodes[0]
  tasks:
  - name: Create a folder for each server
    command: "mkdir -p /root/gluster-logs/{{ item }}-{{ hostvars[item]['ansible_host'] }}"
    with_items: "{{ groups['gluster_nodes'][1:] }}"

  - name: Copy gluster logs
    command: "scp -r root@{{ hostvars[item]['ansible_host'] }}:/var/log/glusterfs /root/gluster-logs/{{ item }}-{{ hostvars[item]['ansible_host'] }}"
    with_items: "{{ groups['gluster_nodes'][1:] }}"

  - name: Copy samba logs
    command: "scp -r root@{{ hostvars[item]['ansible_host'] }}:/var/log/samba /root/gluster-logs/{{ item }}-{{ hostvars[item]['ansible_host'] }}"
    with_items: "{{ groups['gluster_nodes'][1:6] }}"

  - name: Archive the directory
    archive:
      path: "/root/gluster-logs"
      format: gz
      dest: "/root/gluster-logs.gz"
