# vim:ft=ansible:
---
- hosts: localhost
  tasks:
  - name: Create an ssh keypair
    shell: ssh-keygen -b 2048 -t rsa -f $WORKSPACE/glusto -q -N ""
    args:
      creates: "{{ lookup('env', 'WORKSPACE')}}/glusto"

- hosts: gluster_nodes[0]
  tasks:
  - name: Copy ssh key
    copy: src="{{ lookup('env', 'WORKSPACE') }}/glusto" dest=/root/.ssh/id_rsa mode=600

  - name: Install nginx
    yum: name={{ item }} state=installed
    with_items:
    - nginx

  - name: Install the nginx config file
    copy:
      src: nginx.conf
      dest: /etc/nginx/conf.d/default.conf

  - name: Create /var/www
    file:
      path: /var/www
      state: directory

  - name: Copy packages to /var/www
    command: cp -r /root/glusterfs/RPMS/* /var/www/

- hosts: gluster_nodes[1:]
  tasks:
  - name: Set workspace
    set_fact:
      workspace: "{{ lookup('env', 'WORKSPACE') }}"

  - name: Add entries to authorized_keys
    authorized_key: user=root key="{{ lookup('file', workspace + '/glusto.pub')}}"

- hosts: gluster_nodes
  tasks:
  - name: Setup EPEL
    yum: name=epel-release state=installed

# Server and client tasks
- hosts: gluster_nodes[1:8]
  tasks:
  - name: Disable ipv6 in eth0 config
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: ^IPV6INIT=
      line: IPV6INIT=no

  - name: Disable ipv6 in network config
    lineinfile:
      dest: /etc/sysconfig/network
      regexp: ^NETWORKING_IPV6=
      line: NETWORKING_IPV6=no

  - name: Disable ipv6 in sysctl
    sysctl:
      name: "{{ item }}"
      value: 1
      state: present
      reload: yes
    with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

  - name: Stop Firewall
    service: name=firewalld state=stopped

  - name: Flush iptables
    command: "iptables -F"

  - name: Flush iptables
    command: "iptables -X"

  - name: Install dependency packages
    yum: name={{ item }} state=installed
    with_items:
    - nfs-utils
    - cifs-utils

# Set up servers
- hosts: gluster_nodes[1:6]
  tasks:

  - name: Install dependency packages
    yum: name={{ item }} state=installed
    with_items:
    - qemu-img
    - libibverbs

  - name: Setup {{ g_branch }} repo
    yum_repository:
      name: gluster_nightly
      description: The nightly repo for Gluster
      baseurl: "{{ http://hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
      gpgcheck: no
      repo_gpgcheck: no

  - name: Install gluster
    yum: name={{ item }} state=installed
    with_items:
    - glusterfs-server
    - glusterfs-cli
    - glusterfs-debuginfo

  - name: Create the qemu-image
    command: "qemu-img create -f raw /var/{{item}} 50G"
    args:
      creates: "/var/{{item}}"
    with_items:
    - data1
    - data2
    - data3
    - data4

  - name: Run parted
    command: "parted /var/{{item}} mklabel gpt --script"
    with_items:
    - data1
    - data2
    - data3
    - data4

  - name: Assign full space to one partition
    command: "parted -a optimal /var/{{item}} mkpart p ext2 1024 100% --script"
    with_items:
    - data1
    - data2
    - data3
    - data4

  - name: Get the partition up
    command: "kpartx -avs /var/{{item}}"
    args:
      creates: "/dev/mapper/{{item}}"
    with_items:
    - data1
    - data2
    - data3
    - data4

  - name: Run mkfs
    shell: "mkfs.xfs -f /dev/mapper/{{item}}"
    ignore_errors: yes
    with_items:
    - loop0p1
    - loop1p1
    - loop2p1
    - loop3p1

  - name: Mount the bricks
    mount: name="/mnt/{{item.0}}" src="/dev/mapper/{{item.1}}" state=mounted fstype=xfs
    with_together:
    - ['vol0', 'vol1', 'vol2', 'vol3']
    - ['loop0p1', 'loop1p1', 'loop2p1', 'loop3p1']

  - name: Start Gluster Daemon
    service: name=glusterd state=started

  - name: Status rpcbind
    service: name=rpcbind state=started

# Setup client
- hosts: gluster_nodes[7:8]
  tasks:
  - name: Install dependency packages
    yum: name={{ item }} state=installed
    with_items:
    - python-pip
    - libxml2-devel
    - libxslt-devel
    - gcc
    - python-devel
    - fuse
    - fuse-libs

  - name: Setup {{ g_branch }} repo
    yum_repository:
      name: gluster_nightly
      description: The nightly repo for Gluster
      baseurl: "{{ http://hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
      gpgcheck: no
      repo_gpgcheck: no

  - name: Install gluster
    yum: name={{ item }} state=installed
    with_items:
    - glusterfs-fuse

  - name: Install python-docx
    pip: name=python-docx state=present

- hosts: gluster_nodes[1]
  tasks:
  - name: Peer probe all nodes
    command: "gluster peer probe {{hostvars[item]['ansible_eth0']['ipv4']['address']}}"
    with_items: "{{groups['gluster_nodes'][2:7]}}"

  - name: Install dependency packages
    yum: name={{ item }} state=installed
    with_items:
    - ctdb
    - samba
    - samba-vfs-glusterfs
    - samba-client

  - name: Start smb
    service: name=smb state=started

  - name: Setup SELinux for Samba
    seboolean: name=samba_load_libgfapi state=yes persistent=yes

  - name: Setup SELinux in permissive mode
    selinux: policy=targeted state=enforcing

  - name: Setup Samba credentials
    shell: (echo "foobar"; echo "foobar") | smbpasswd -a root
  - name: Setup Samba configuration
    blockinfile:
      dest: /etc/samba/smb.conf
      insertafter: '\[global\]'
      content: |
          kernel share modes = no
          kernel oplocks = no
          map archive = no
          map hidden = no
          map read only = no
          map system = no
          store dos attributes = yes
    tags: smb

- hosts: gluster_nodes[0]
  tasks:
  - name: Copy ssh key
    copy: src="{{ lookup('env', 'WORKSPACE') }}/glusto" dest=/root/.ssh/id_rsa mode=600

  - name: Install git and pip
    yum: name="{{item}}" state=present
    with_items:
    - git
    - python-pip

  - name: Set glusto version
    set_fact:
      GERRIT_REF: "{{ lookup('env', 'GERRIT_REF') }}"

  - name: Install Glusto
    pip: name=' git+git://github.com/loadtheaccumulator/glusto.git' editable=false

  - name: Clone the gluster-tests repo - {{ GERRIT_REF}}
    git:
        repo: git://review.gluster.org/glusto-tests.git
        dest: /root/glusto-tests
        refspec: "+refs/changes/{{GERRIT_REF}}:refs/remotes/origin/changes/{{GERRIT_REF}}"
        version: FETCH_HEAD
    when: GERRIT_REF != 'master'

  - name: Clone the gluster-tests repo
    git:
        repo: git://review.gluster.org/glusto-tests.git
        dest: /root/glusto-tests
        version: "{{GERRIT_REF}}"
    when: GERRIT_REF == 'master'

  - name: Install glustolibs
    command: "python setup.py develop chdir=/root/glusto-tests/{{item}}"
    with_items:
    - glustolibs-gluster
    - glustolibs-io
    - glustolibs-misc

  - name: Create the config file
    template: src=templates/gluster_tests_config.yml.j2 dest=/root/gluster_tests_config.yml
